### ISSUE TITLE
Support moving of properties

### ISSUE THREAD

**Issue by JohnCPun** [gogognome/gogomessagepropertiessynchronizer#1]
In the source and destination file add a property at line x.
Now in the source file move this property to another line, without changing the key of the property.

Run synchronizer.

In the destination file it deletes the line at the original location (including translation) and adds a new line (with a TODO) on the new location.
It would be nice if it would add the line on the new location with the original translation.

**Comment by gogognome** [comment]
This feature has been implemented in version 1.0.1.
