### ISSUE TITLE
Support renaming of properties

### ISSUE THREAD

**Issue by JohnCPun** [gogognome/gogomessagepropertiessynchronizer#2]
In the source and destination file add a property at line x.
Now in the source file rename this property, without changing the line and translation of the property.

Run synchronizer.

In the destination file it deletes the original property (including translation) and adds a new line in the same place (with a TODO) on the new key.
It would be nice if it would change the key of the property.

**Comment by gogognome** [comment]
There is no way for the tool to determine the difference between renaming the property at line x and deleting and inserting a new property at line x.
The way you suggest seems that the tool should keep a copy of the file of the previous run.
